kind: pipeline
type: docker
name: build

volumes: # 声明数据卷
- name: code
  host:
    path: /volumes/drone/code
- name: node_modules # 数据卷名称
  host: # Host Volume
    path: /volumes/drone/node_modules # 宿主机目录
- name: docker
  host:
    path: /var/run/docker.sock
clone:
  disable: false # 启用拉取

steps:
  - name: build-fronted # 构建前端
    image: node:latest # 使用镜像
    depends_on: [clone] # 依赖的步骤
    volumes: # 挂载数据卷
    - name: node_modules # 数据卷名称
      path: /drone/src/vue-element-admin-new/node_modules # 容器内目录 绝对路径
    commands: # 执行命令
      - cd /drone/src/
      - ls
      - cd /drone/src/vue-element-admin-new/ #
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - git config --global http.sslverify "false"
      - git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
      - npm install # 安装node_modules包
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm run build:stage # 执行编译   
  
  - name: deploy-project
    image: appleboy/drone-ssh
    volumes: # 挂载数据卷
    - name: code # 数据卷名称
      path: /drone/src # 容器内目录 绝对路径
    settings:
      # 部署主机的IP  
      host: 121.4.54.4
      # 部署主机的登录账号，需从Drone中获取密钥名ssh_user的值，创建方式见下面
      username:
        from_secret: ssh_user
      # 部署主机的登录密码，需从Drone中获取密钥名ssh_pwd的值，创建方式见下面
      password:
        from_secret: ssh_pwd
      # 端口号
      port: 22
      # 设置超时
      command_timeout: 30m
      # 编写脚本，可根据具体情况编写
      depends_on: [build-fronted]

  # - name: build-docker
  #   image: plugins/docker
  #   volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
  #     - name: code
  #       path: /drone/src/* # 将应用打包好的Jar和执行脚本挂载出来
  #     - name: docker
  #       path: /var/run/docker.sock # 挂载宿主机的docker
  # - name: code-scp    # 将代码文件放入指定目录
  #   image: appleboy/drone-scp
  #   depends_on: [build-fronted]
  #   settings:
  #     # 部署主机的IP  
  #     host: 121.4.54.4
  #     # 部署主机的登录账号，需从Drone中获取密钥名ssh_user的值，创建方式见下面
  #     username:
  #       from_secret: ssh_user
  #     # 部署主机的登录密码，需从Drone中获取密钥名ssh_pwd的值，创建方式见下面
  #     password:
  #       from_secret: ssh_pwd
  #     # 端口号
  #     port: 22
  #     # 设置超时
  #     command_timeout: 30m
  #     target: /volumes/drone/code/
  #     source: ./
      
      
      # 编写脚本，可根据具体情况编写
  #     script:
  #       - echo ====开始部署=======
  #       - echo ====拉取代码=======
  #       - cd /TestProject
  #       - echo ====重新构建镜像=======
  #       - cd /TestProject
  #       - docker-compose stop
  #       - docker-compose build
  #       - echo ====重新启动容器=======
  #       - docker-compose up -d
  #       - echo ====删除所有为None的镜像=======
  #       - docker rmi $(docker images -f "dangling=true" -q)
  #       - echo ====清除日志/无用镜像、容器、卷======
  #       - cat /dev/null > *-json.log
  #       - docker system prune -f
  #       - echo =======部署结束=======
