# kind: pipeline
# type: docker
# name: deploy

# clone:
#   disable: true # 禁用拉取

# steps:
#   - name: deploy-project
#     image: appleboy/drone-ssh
#     settings:
#       # 部署主机的IP  
#       host: 121.4.54.4
#       # 部署主机的登录账号，需从Drone中获取密钥名ssh_user的值，创建方式见下面
#       username:
#         from_secret: ssh_user
#       # 部署主机的登录密码，需从Drone中获取密钥名ssh_pwd的值，创建方式见下面
#       password:
#         from_secret: ssh_pwd
#       # 端口号
#       port: 22
#       # 设置超时
#       command_timeout: 10m
#       # 编写脚本，可根据具体情况编写
#       script:
#         - echo ====开始部署=======
#         - echo ====拉取代码=======
#         - cd /TestProject
#         - which git
#         - git pull origin main
#         - echo ====安装前端依赖======
#         - cd /TestProject/vue-admin-template
#         - npm install --registry=https://registry.npm.taobao.org
#         - export NODE_OPTIONS=--openssl-legacy-provider
#         - echo ====打包前端项目======
#         - npm run build:stage
#         - echo ====重新构建镜像=======
#         - cd /TestProject
#         - docker-compose stop
#         - docker-compose build
#         - echo ====重新启动容器=======
#         - docker-compose up -d
#         - echo ====删除所有为None的镜像=======
#         - docker rmi $(docker images -f "dangling=true" -q
#         - echo =======部署结束=======


---
kind: pipeline
type: ssh
name: default

server:
  # 部署主机的IP  
  host: 121.4.54.4
  # 部署主机的登录账号，需从Drone中获取密钥名ssh_user的值，创建方式见下面
  username:
    from_secret: ssh_user
  # 部署主机的登录密码，需从Drone中获取密钥名ssh_pwd的值，创建方式见下面
  password:
    from_secret: ssh_pwd
  # 端口号
  port: 22

steps:
- name: greeting
  commands:
  - echo hello world
