kind: pipeline
type: docker
name: build

workspace:
  path: /drone/src

volumes: # 声明数据卷
- name: site-packages #后端依赖包
  host:  # Host Volume
    path: /volumes/drone/site-packages/ # 宿主机目录
- name: node_modules # 前端依赖包
  host: 
    path: /volumes/drone/node_modules  # 宿主机目录
- name: dist
  host:
    path: /volumes/drone/dist

clone:
  disable: false # 启用拉取

steps:
  - name: build-fronted-dep # 构建前端
    image: node:latest # 使用镜像
    depends_on: [clone] # 依赖的步骤
    volumes: # 挂载数据卷
    - name: node_modules # 数据卷名称
      path: /drone/src/vue-element-admin-new/node_modules # 容器内目录 绝对路径
    - name: dist
      path: /drone/src/vue-element-admin-new/dist
    commands: # 执行命令
      - cd /drone/src/vue-element-admin-new/ #
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - git config --global http.sslverify "false"
      - git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
      - npm install # 安装node_modules包
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm run build:stage # 执行编译   
      # - cp -f /drone/src /myproject -r 



