---
kind: pipeline
type: ssh
name: test

server:
  host: 121.4.54.4
  user: root
  port: 22
  password: 
    from_secret: ssh_password

clone:
  disable: true

steps:
- name: greeting
  commands:
  - echo hello world