kind: pipeline
type: docker
name: test

clone:
  disable: false # 启用代码拉取

steps:
  - name: fronted_build # 步骤名称
    image: nginx # 使用镜像
    depends_on: [clone] # 依赖的步骤，
    commands: # 当前步骤执行的命令
      - npm install
      - npm run build:stage