kind: pipeline
type: docker
name: deploy

volumes: # 声明数据卷
  - name: node_modules # 数据卷名称
    host: # Host Volume
      path: /volumes/drone/node_modules # 宿主机目录
clone:
  disable: false # 启用拉取

steps:
  # - name: pull_fronted_git #挂载前端git代码至宿主机
  #   image: drone/git
  #   depends_on: [clone]
  - name: build-fronted # 安全前端依赖 
    image: node:latest # 使用镜像
    depends_on: [clone] # 依赖的步骤
    volumes: # 挂载数据卷
      - name: node_modules # 数据卷名称
        path: /drone/src/vue-element-admin-new/node_modules # 容器内目录 绝对路径
    commands: # 执行命令
      - cd /drone/src/vue-element-admin-new/ #
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
      - npm install # 安装node_modules包
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm run build:stage # 执行编译
