# Generated by Django 4.0.6 on 2022-12-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission_api',
            old_name='permission_id',
            new_name='permission',
        ),
    ]
