# Generated by Django 4.0.6 on 2023-02-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rolepermission', '0003_alter_permission_api_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='permission_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='菜单名')),
                ('path', models.CharField(default='', max_length=100, verbose_name='路径名')),
                ('component', models.CharField(default='', max_length=80, verbose_name='组件')),
                ('icon', models.CharField(default='', max_length=20, verbose_name='icon名')),
                ('parent_id', models.IntegerField(verbose_name='父节点ID，默认为0')),
                ('is_delete', models.IntegerField(default=0, verbose_name='是否删除，默认为0')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='permission_role_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolepermission.permission_menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
