# Generated by Django 4.0.6 on 2023-02-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rolepermission', '0004_permission_menu_permission_role_menu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission_role_menu',
            unique_together={('role', 'menu')},
        ),
    ]
