# Generated by Django 4.0.6 on 2023-02-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0005_alter_permission_role_menu_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission_menu',
            old_name='name',
            new_name='title',
        ),
    ]
