# Generated by Django 4.0.6 on 2023-02-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0006_rename_name_permission_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_menu',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
