# Generated by Django 4.0.6 on 2022-11-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoJobExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(null=True, verbose_name='描述')),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.djangojob')),
            ],
        ),
    ]
