# Generated by Django 4.0.6 on 2022-11-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoJobExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(verbose_name='描述')),
                ('excutefun', models.CharField(default='', max_length=50, verbose_name='执行函数')),
                ('trigger', models.CharField(default='', max_length=50, verbose_name='触发类型')),
                ('crontab', models.CharField(default='', max_length=50, verbose_name='触发时间')),
                ('state', models.BooleanField(default=1, verbose_name='是否开启')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler.djangojob')),
            ],
        ),
    ]
