# Generated by Django 4.0.6 on 2022-12-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangojobextend',
            options={'default_permissions': ()},
        ),
    ]
