# Generated by Django 4.0.6 on 2022-11-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangojobextend',
            old_name='jobid',
            new_name='job',
        ),
    ]
