# Generated by Django 4.0.6 on 2022-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled', '0002_rename_jobid_djangojobextend_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangojobextend',
            name='excutefun',
            field=models.CharField(default='', max_length=50, verbose_name='执行函数'),
        ),
        migrations.AddField(
            model_name='djangojobextend',
            name='trigger',
            field=models.CharField(default='', max_length=50, verbose_name='触发类型'),
        ),
        migrations.AlterField(
            model_name='djangojobextend',
            name='describe',
            field=models.TextField(verbose_name='描述'),
        ),
    ]
