# Generated by Django 4.0.6 on 2022-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled', '0003_djangojobextend_excutefun_djangojobextend_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangojobextend',
            name='crontab',
            field=models.CharField(default='', max_length=50, verbose_name='触发时间'),
        ),
    ]
