# Generated by Django 4.0.4 on 2022-10-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('code', models.CharField(max_length=50, verbose_name='邮箱授权码')),
                ('server', models.CharField(max_length=50, verbose_name='服务器地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('keyword', models.CharField(default='', max_length=50, verbose_name='关键字')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SearchReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='测试报告名称')),
                ('sender', models.CharField(max_length=50, null=True, verbose_name='发送人')),
                ('receive', models.CharField(max_length=50, null=True, verbose_name='接收人')),
                ('text', models.TextField(null=True, verbose_name='正文')),
                ('report_time', models.DateField(null=True, verbose_name='报告时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.projectmanage')),
            ],
        ),
    ]
