# Generated by Django 4.0.6 on 2022-12-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmanage',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='projectmanage',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='searchreportlog',
            options={'default_permissions': ()},
        ),
    ]
