# Generated by Django 4.0.4 on 2022-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchreportlog',
            name='lastest',
            field=models.BooleanField(default=True, verbose_name='是否最新'),
        ),
    ]
