# Generated by Django 4.0.4 on 2022-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchreportlog',
            name='existfail',
            field=models.BooleanField(default=False, verbose_name='报告是否存在错误'),
        ),
    ]
