# Generated by Django 4.0.4 on 2022-10-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_searchreportlog_lastest'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchreportlog',
            name='report_dir',
            field=models.CharField(max_length=500, null=True, verbose_name='报告路径'),
        ),
    ]
